{
 "title": "Tracking",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Itens enfileirados (total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "queue_enqueued_total{job=\"api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Itens processados (total)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "queue_processed_total{job=\"workers\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Itens enfileirados por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "rate(queue_enqueued_total{job=\"api\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Processamentos por segundo",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "rate(queue_processed_total{job=\"workers\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tempo médio de processamento (segundos)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(queue_processing_seconds_sum{job=\"workers\"}[1m]) / (rate(queue_processing_seconds_count[1m]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}